urlspoiledcards: "https://api.scryfall.com/cards/search?order=spoiled&unique=prints&q=e%3A"
urlsets: "https://api.scryfall.com/sets/"
setsfile: "data/sets-to-watch.json"
cardcountsfile: "data/set-card-counts.json"
sleeptime: 0.2
updateinterval_min: 30
updatespaminterval_s: 15
charlimit: 2000
verbose: true